
project_id = "drmdytzmpasgxgsutvbi"

[functions.stripe-webhooks]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true
