// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmdytzmpasgxgsutvbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybWR5dHptcGFzZ3hnc3V0dmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzMzMzMsImV4cCI6MjA2NTA0OTMzM30.bTDLEwKXZqwR8m2gltf6VS2EqocMwnLo6MeShcMeHE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);